- public/config.json
- src/App.tsx
- src/components/AppLayout/AppLayout.tsx
- src/components/ThemePreview/ThemePreview.tsx
- src/components/ThemePreview/index.tsx
- src/pages/About.tsx
- src/pages/Compose.tsx
- src/pages/Missingno.tsx
- src/pages/Notifications.tsx
- src/pages/PageLayout.styles.tsx
- src/pages/Recommendations.tsx
- src/pages/Settings.tsx
- src/pages/Welcome.tsx
- src/pages/WelcomePage.styles.tsx
- src/types/Config.tsx
- src/types/HyperspaceTheme.tsx
- src/types/Visibility.tsx
- src/utilities/settings.tsx
- src/utilities/themes.tsx
* A new `location` field in the config file should help mitigate redirect URL issues that cause client authentication errors. (#8)
* The notification badge will now be displayed on mobile devices in the menu and should no longer disappear and lose count with the setting "Notification badge counts all notifications'' turned on (fixes #7).
* The theme chooser has been slightly redesigned to include a new theme preview before applying the theme.
* A new setting is available to set the default visibility when composing new posts.
* The drawer menu on mobile devices has been reorganized in a logical manner.
* A new setting that allows the app to follow the browser's/platform's light mode/dark mode preference has been added.
* A few changes have been made to …
> Beta 2 updates

- README.md
- src/pages/Notifications.tsx
* Streams notifications and adds new ones as they arrive (fixes #19)
* Adds a reply button to notifications that are of the type `mention` (eg. messages, replies to existing posts, new posts with a mention, etc.)
> Stream notifications and reply button on mention-related notifs

- src/pages/Welcome.tsx
- src/pages/WelcomePage.styles.tsx
* Fixes the issue where the Authorize button on the login page appears ghosted (fixes #24).
* Changes the helper text on landing to _Not from <instance.domain>? Sign in with your full username._ with a link to "Addressing people" from Mastodon docs to assist.
* Adds version text to bottom of login dialog.
> Spruce up login page

- src/pages/Notifications.tsx
- src/pages/PageLayout.styles.tsx
- src/pages/Recommendations.tsx
- src/pages/Search.tsx
- src/types/HyperspaceTheme.tsx
This PR makes the following changes: 
- Changes the Attract theme colors to prevent CSS collisions with existing Material-UI components (fixes #26).
- Adds an `pageLayoutEmptyTextConstraints` CSS class to PageLayout styles (fixes #27).
- Updates the search query on accounts so that "No results found" is displayed instead of empty paper.
- Removed the King theme and replaced with the Classic theme.
> Update themes and empty text padding CSS

- src/pages/Compose.tsx
- src/pages/Settings.tsx
- src/pages/Welcome.tsx
This PS makes the following changes (fixes #28):
* Disables public visibility on compose window and in settings
* Tightens/strict checks on username input when logging in, only allowing login to the instance listed in `config.json`
* Hides "Not from <instance name>?" text when defederated
> More control on defederation settings

- src/pages/Welcome.tsx
* Fixes the well-known login that failed to work due to a faulty check in determining federation status from `config.json`.
> Fix well-known login caused by faulty check in federation status

- src/pages/Compose.tsx
* Adds a key to the "Uploading media..." snackbar in the media uploader and closes in both the `then` and `catch` function calls (fixes #32)
* Displays "Couldn't upload media" as the `error` variant
> Fix persistent media upload snackbar

- src/pages/About.tsx
- src/pages/PageLayout.styles.tsx
- Redesigns the instance information to display admin, terms of service, invite links, and Mastodon version (fixes #46)
- Displays instance thumbnail on top of card
- Removes "About your instance" text
> Redesign "About your instance"

- src/pages/About.tsx
- src/pages/PageLayout.styles.tsx
- Introduces new redesign for app info, matching #48 
- Federation set to own category (to display specifics later)
> App info redesigned

- README.md
- patreon.md
This PR makes the following change:
- Adds a `patreon.md` file to thank all of the Patreon subscribers for their support on Hyperspace (and links it on the README).
This PR does not make any changes to the existing codebase and should not affect the app in any way.
> Add Patreon contributors list

- src/components/AppLayout/AppLayout.tsx
- src/components/Post/Post.tsx
- Fixes any problems caused by #61 by converting `isDesktopApp` to the function rather than a variable
- Hides the card media when images/videos are present (fixes #47)
- Truncates media descriptions that are more than 500 characters in length and adds ellipses when necessary
> Make cards smaller when possible

- README.md
- Format a directory name to make it harder to overlook
- Fix one instance of `npm run electrify-nobuild` mistyped as `npm run electrify`
> Slighly improve README: format a directory name and fix a command name

- src/pages/About.tsx
- src/utilities/accounts.tsx
- Removes (the check for) the instance's contact account from the About page to let it complete loading.
- A check is created to determine if the instance being used is a Pleroma instance, stored in `localStorage['isPleroma']` as "true" or "false" (strings).
- Fixes #69 , improves #65 
> Note: This PR comment has been edited to match Hyperspace Contribution Guidelines by @alicerunsonfedora .
> Pleroma support (fixes #69)

- .github/FUNDING.yml
- Adds `FUNDING.yml` as a way for GitHub users to sponsor Hyperspace
> Add GitHub sponsorship information

- public/config.json
- public/electron.js
- src/App.tsx
- src/components/AppLayout/AppLayout.tsx
- src/components/Post/Post.tsx
- src/index.tsx
- src/pages/Compose.tsx
- src/pages/PageLayout.styles.tsx
- src/pages/Welcome.tsx
- src/pages/You.tsx
- src/types/Account.tsx
- src/utilities/accounts.tsx
- Adds a new `MultiAccount` type to store access token, username, and base URL.
- Adds new utilities that interact with localStorage key `accountRegistry` to add, login with, and remove accounts
- Modifies Welcome to now include user switching when visiting the welcome page
- Modifies AppLayout, Post, You, etc. components to dynamically get account information via a GET request to `/accounts/verify_credentials`) and only reads account's local storage as a last resort
- Modifies AppLayout's logout to also remove an account from the registry
- Fixes #37
> Add user-account-switching

- public/electron.js
- src/components/AppLayout/AppLayout.tsx
- Fixes the issue where the desktop apps reload without performing a search when searching something (fixes #100)
- Updates the Electron script to fix some names, licensing, and force the window to show only when the content has loaded
> Fix search loading issues on desktop apps

- src/components/Post/Post.styles.tsx
- src/components/Post/Post.tsx
Signed-off-by: Travis Kohlbeck <me+git@travisk.info>
- adds class to reblog menu div
- adds `outline: none` to post styles
- closes #108
> removes 'focused' outline from reblogged post menu

- src/components/Post/Post.tsx
- Moves the Post's "More" Button's Tooltip from below the Button to the left (adds the value "left" to the attribute "placement")
- Fixes #115
> Moves Tooltip from bottom to left

- package-lock.json
- package.json
- public/electron.js
- src/App.tsx
- src/components/AppLayout/AppLayout.tsx
- src/pages/About.tsx
- src/pages/Activity.tsx
- src/pages/Recommendations.tsx
- src/pages/Requests.tsx
- src/pages/Settings.tsx
- src/types/Account.tsx
- src/types/History.tsx
- src/types/Tag.tsx
- Moves follow requests to its own page at `/requests` (links available in Recommended page, account menu, and Settings)
- Renames "Who to follow" page to "Recommended"
- Adds "Activity" page at `/activity` to let people see trending hashtags, active people, and new arrivals on their instance
- Updates Material UI icons package to 4.5.1
- Updates the Account and Tag types, as well as introduces the History type
> Add Activity page

- package-lock.json
- package.json
- src/pages/About.tsx
- Changed strings from "Hyperspace" to "Hyperspace Desktop" in the about page and package.json
- Closes [HD-12]
- Edited start script by removing HTTPS env var
[HD-12]: https://hyperspacedev.atlassian.net/browse/HD-12
> HD-12 Brand rename

- src/index.tsx
- src/pages/About.tsx
- src/utilities/accounts.tsx
- Makes Pleroma check more dynamic on About page by calling `shouldRenderInstanceContact` method instead of reading from localStorage
- Fixes #69 caused by a regression in account storage settings when making multi-accounts
- Removes `isPleroma` localStorage check in favor of `shouldRenderInstanceContact`
- Removes checking for `account` key changes in localStorage to prevent infinite reloading
- Closes [HD-17]
[HD-17]: https://hyperspacedev.atlassian.net/browse/HD-17
> [HD-17] Fix Pleroma about page blank regression

- src/pages/Compose.tsx
- src/pages/Settings.tsx
- src/utilities/settings.tsx
- Adds a new setting key, `imposeCharacterLimit`, to determine whether the default character limit should be imposed (defaults to `true`)
- Adds the settings entry in the Settings page as "Impose character limit"
- Changes the composer window to display a warning instead of the character limit when the limit is turned off
- Changes the default limit when `imposeLimitCharacter` is turned off in Composer to `99999999`
- Closes [HD-19] and #125 
[HD-19]: https://hyperspacedev.atlassian.net/browse/HD-19
> [HD-19] Toggle-able Character Limit

- README.md
- package-lock.json
- src/pages/Welcome.tsx
- Adds an additional check on the `authorizeEmergencyLogin()` method for if the default redirect address is set to "desktop" and change the redirect address
- Fixes [HD-23] and #129
- Updates README by removing Mac App Store links and providing a link to our [explanation post](https://hyperspace.marquiskurt.net/2019/11/08/post.html)
[HD-23]: https://hyperspacedev.atlassian.net/browse/HD-23
> [HD-23] Emergency login fix

- package-lock.json
- package.json
- src/components/AppLayout/AppLayout.tsx
- src/pages/Activity.tsx
- src/pages/Messages.tsx
- src/pages/Notifications.tsx
- src/pages/Recommendations.tsx
- Modifies the Messages, Recommendations, and Activity pages to display a similar iconified design to the follow requests page when it's empty
- Fixes the Activity page icon's color from black to `inherit`
- Updates the titlebar in dev mode with a Material Design wrench instead of an emoji
- Updates TypeScript dependency to 3.7.2
> Update empty pages with new iconified design

- package-lock.json
- src/components/EmojiPicker/index.tsx
- Modifies the `retireveFromLocal` function in `EmojiPicker` to return `undefined` when the localStorage item is null/missing.
- Fixes [HD-21]
> Note: should be tested on a server that does _not_ have custom emojis.
[HD-21]: https://hyperspacedev.atlassian.net/browse/HD-21
> [HD-21] Stop emoji picker event crashes

- src/pages/Settings.tsx
> ⚠️ **Note**: This PR also covers changes for #140. Changes for both PRs _must_ be approved in order for this PR to be merged. - @alicerunsonfedora 
- A ternary operator would either render a loaded profile header, or render nothing. This change renders a loaded profile header, or a "loading" profile header, keeping the rest of the page in the same position. Fixes #142 
- Two prettier formatting changes. Couldn't figure out how to disable this but I guess it follows the formatting guidelines?
Here is what it looks like:
> [HD-30] Adds dummy header to Settings page to prevent layout reposition

- .github/workflows/ci-mac.yml
- Adds a conditional on the certificate install step in `ci-mac` to only run if a member from the Desktop team initiates it.
> Run certificate installs on CI only if Desktop initiates it

- src/components/Post/Post.styles.tsx
- src/components/Post/Post.tsx
- Removes parens and changes color of author account name
- Replaces reblog emoji with an icon
Before:
After:
Light:
I tried to get the account name color to match the timestamp (timestamp is `<Typography color="textSecondary" />`, but was unable to inline `<Typography />` so I settled for `palette.grey[500]`. It may be a bit too light for the light theme :(
I also couldn't figure out how to apply prettier to just a section and not the whole file (vscode was not cooperating) so I apologize for any formatting mistakes.
> Updates appearance of post/retoot authors

- src/pages/Compose.styles.tsx
- src/pages/Compose.tsx
- src/types/Draft.tsx
- src/utilities/compose.tsx
- Add utilities to load and save unsaved text (and reply ID) to `sessionStorage`
- Add a Draft type to accommodate for utilities
- Add UI to load a draft from `sessionStorage`
- Save unsaved text to `sessionStorage` as a cached draft when unmounting the Compose page
- Fixes [HD-7] and #114 
> Note: This feature is _not_ designed for long-term storage. Cached drafts clear when the browser window or tab is closed.
[HD-7]: https://hyperspacedev.atlassian.net/browse/HD-7
> [HD-7] Add cached drafts

- src/components/AppLayout/AppLayout.styles.tsx
- src/components/AppLayout/AppLayout.tsx
- src/utilities/appbar.tsx
- Adds a back button to AppLayout
- Introduces `isChildView` utility and `childViews` list for views that are considered "children" (thus far, conversations and profiles)
- Adds documentation to AppLayout page
- Addresses https://github.com/hyperspacedev/hyperspace/issues/136#issuecomment-563479232
- Fixes [HD-28]
> Note: this PR only affects the desktop apps. Users can use the browser's native back button if they're viewing the page on the web.
[HD-28]: https://hyperspacedev.atlassian.net/browse/HD-28
> [HD-28] Add a back button for child views

- src/components/AppLayout/AppLayout.styles.tsx
- src/pages/Compose.tsx
- Fixes an issue where the upload media function would run on every copy/paste, including non-image clipboard contents (fixes [HD-25])
- Adds documentation to the Compose page with JSDoc
- Renames `actuallyUploadMedia` to `uploadMedia` and the old `uploadMedia` to `promptMediaDialog`
- Adds `getContrastText` to `titleBarText` class in `AppLayout` to make sure it uses the correct colors in the titlebar.
[HD-25]: https://hyperspacedev.atlassian.net/browse/HD-25
> [HD-25] Fix clipboard event firing and update Compose docs

- src/components/Post/Post.tsx
- Re-implements `getReblogAuthors` to properly display images in-line via `dangerouslySetInnerHTML` (Mastodon HTML should already be sanitized, and the only HTML we inject would be fore emojis)
- Fixes regression from #144 
- Addresses #154 and fixes [HD-39]
[HD-39]: https://hyperspacedev.atlassian.net/browse/HD-39
> [HD-39] Fix appearance of author names

- src/App.tsx
- src/interfaces/overrides.tsx
- src/pages/Home.tsx
- src/pages/Local.tsx
- src/pages/Public.tsx
- src/pages/Timeline.tsx
- Creates a new `TimelinePage` component that simplifies timeline page development
- Updates `PrivateRoute` to allow `render` as a valid property
- Replaces `HomePage`, `LocalPage`, and `PublicPage` in the main App file with `TimelinePage`
- Marks `HomePage`, `LocalPage`, and `PublicPage` as deprecated
- Implements [HD-35]
[HD-35]: https://hyperspacedev.atlassian.net/browse/HD-35
> [HD-35] Simplify Timeline page code

- src/components/Attachment/Attachment.tsx
- Uses `video` element to render gifs
- Replaces `alt` attribute with `title`
- fixes #157 and [HD-41](https://hyperspacedev.atlassian.net/browse/HD-41?atlOrigin=eyJpIjoiMjNkMDJlNjg2MTZmNGNlN2JlYzk1N2FjZDVmOTI0MGEiLCJwIjoiaiJ9)
> [HD-41] loads and loops gif/mp4 "images"

- src/pages/PageLayout.styles.tsx
- src/pages/ProfilePage.tsx
- src/pages/Search.tsx
- Adds masonry layout to Profile Page
- Adds masonry layout to Search Page, accommodating Account display
- addresses #150 and [HD-36](https://hyperspacedev.atlassian.net/browse/HD-36?atlOrigin=eyJpIjoiZTE4ODBhODVlYjJhNDNhNzk2ZjJhZDVjZGUwOTFlZjYiLCJwIjoiaiJ9)
> [HD-36] Enable masonry layout for Search and Profile pages

- src/pages/Compose.tsx
- Updates the `post` method in `Compose` to clear the text field after posting a message and before going back.
- Fixes [HD-48] and #166 
[HD-48]: https://hyperspacedev.atlassian.net/browse/HD-48
> [HD-48] Clear text field in state after posting in Compose

- src/interfaces/overrides.tsx
- src/interfaces/utils.tsx
- src/pages/Notifications.tsx
- src/pages/Welcome.tsx
- src/utilities/login.tsx
- Fixes a bug in the Welcome page where the redirect address would be `null` or `undefined` because the state wasn't loaded (workaround: used `getConfig()`)
- Changes notification appearance in Notifications to show a menu on mobile devices or smaller screens
- Adds a pop-up menu when clicked on mobile
- Hides the standard buttons when on a small screen
- Manages menu notification state with a dictionary of values
- Adds a Generic `Dictionary` type to specify the types of dictionaries
> [HD-46] Optimize notifications on smaller device screens

- src/components/Post/Post.tsx
- Allows posts to be un/favorited and un/reblogged without refresh
- Allows reblogged posts to unreblog its original post
- Fixes #146 and `HD-31`
-
> [HD-31] Fix reblogging and favorite state update issues

- src/pages/Notifications.tsx
- Stores relationships of notification accounts in state
- Allows unfollowing/toggling from notifications page
- Updates icon and menu label based on un/follow state
- Closes #162 and [HD-45](https://hyperspacedev.atlassian.net/browse/HD-45?atlOrigin=eyJpIjoiMGEwNzdlNTU2NjRiNGUwMWE3ODA0OTIyOTBjM2JlZDQiLCJwIjoiaiJ9)
Made state.relationships mandatory, is this a poor practice? state.notifications is optional/unassigned until willMount...
> [HD-45] Allows unfollowing from the Notifications page

- src/components/Post/Post.styles.tsx
- src/components/Post/Post.tsx
- Prevents author display name from wrapping onto multiple lines.
- Truncates author names line with ellipsis for smaller screens.
- Correctly colors the author account name.
- Resolves #175 and HD-49
> [HD-49] Fixes post author name overflow behavior

- src/utilities/settings.tsx
- Updates the `getConfig` function to automatically change the location field in a config to `"http://localhost:3000"` if being run through `react-scripts` (via checking `process.env.NODE_ENV`)
- Changes console warns in `getConfig` to console info
> Auto-set localhost:3000 URL when testing

- src/App.tsx
- src/components/AppLayout/AppLayout.tsx
- src/pages/Announcements.tsx
- src/types/Announcement.tsx
- Adds new `Announcement` type and Announcements page (points to `/announcements`)
- Implements [HD-50]
Note: I had to do some digging to see what an announcement looks like API-wise since I could not find that info in the API docs, so some things might be inaccurate.
A sample announcement looks like this: 
[HD-50]: https://hyperspacedev.atlassian.net/browse/HD-50
> [HD-50] Add announcements

- src/App.tsx
- src/components/Attachment/Attachment.tsx
- src/components/AudioPlayer/AudioPlayer.tsx
- src/components/ComposeMediaAttachment/ComposeMediaAttachment.tsx
- src/components/EmojiPicker/index.tsx
- src/components/Post/Post.tsx
- src/pages/Compose.tsx
- src/pages/Messages.tsx
- src/pages/Notifications.tsx
- src/pages/PageLayout.styles.tsx
- src/pages/ProfilePage.tsx
- src/pages/Search.tsx
- src/pages/Settings.tsx
- src/pages/Welcome.tsx
- src/utilities/notifications.tsx
- src/utilities/settings.tsx
- Changes behavior of default setting generation to automatically disable push notifications instead of prompting for permission immediately
- Fixes warnings found with @typescript/eslint
- Make `getNotificationRequestPermission` return a Promise
- Change toggle behavior of push notifications in Settings
- If no permissions were set, prompt for permission
- Otherwise, read from the set permission
- Adds anchors to list subheaders in Settings for navigation purposes
- Adds quick link to notification settings on notifications page
- Implements first two tiers of [HD-56]
> Note: This PR relies on #185.
[HD-56]: https://hyperspacedev.atlassian.net/browse/HD-56
> [HD-56] Notification system overhaul (Part 1)

- src/utilities/settings.tsx
- Updates `getConfig` to not apply a backslash when location is set to `desktop` or `dynamic`
> Filter out "desktop" and "dynamic" in location

- package-lock.json
- package.json
- src/pages/About.tsx
- Resolves an issue where config.json doesn't load into the page's state when an admin account isn't loaded correctly by moving non-account state updates to a `finally` statement (fixes #200)
- Reactors parts of the About page to use optional chaining and nullish coalescing
- Adds bug report and feature requests buttons to app card in About
- Rewords "instance" to "copy of Hyperspace" in the Federation status section
- Updates Prettier dependency to support nullish coalescing and optional chaining
> Update about page configurations

- src/pages/Welcome.tsx
- src/utilities/settings.tsx
- Adds an adornment in front of the username field on the Welcome page to prevent sign-in ambiguity
- Refactors parts of the Welcome page to use nullish coalescing and optionals where appropriate
> Add '@' symbol adornment, refactor Welcome

- src/pages/Settings.tsx
- src/utilities/settings.tsx
- Attempts to address or close #206 
- Updates `togglePushNotifications` in Settings.tsx to return if the browser does not support notifications for any given reason:  https://github.com/hyperspacedev/hyperspace/blob/f52daad91c5c2b258880a2afcea7a624c41f195e/src/pages/Settings.tsx#L220-L222
> Return out of notification toggle when browser is unsupported

- src/pages/Blocked.tsx
- src/pages/Welcome.tsx
**Changes Overview**  
- Updates the checkForErrors and startLogin methods with parameters to bypass the validation check with instances.social.
- **Note**: This check occurs _after_ the method checks that the instance domain is not in the disallowed domains list.
- Resolves formatting in some files.
- Updates welcome documentation.
- Displays a snackbar error if the registration to an instance domain fails.
**Does this PR fix, close, or implement any issues?**  
- Fixes #226 
**Pending for review**  
@hyperspacedev/desktop
> Added instance name validation bypass
